# ::::::::::::::::::::::
# Dockerfile.03
# ::::::::::::::::::::::
# Running Ubuntu Image on Docker

FROM ubuntu:16.04

RUN apt-get update
RUN apt-get -y install python3

RUN mkdir /app
WORKDIR /app

COPY index.html index.html

COPY . .
LABEL maintainer="Andialy Sokone<asokone@thecloudedu.com>" \
version="1.0"

CMD python3 -m http.server 5000
